### ISSUE TITLE
Error cannot convert from 'const char *' to 'char *' / LOAD_IMVEC2s

### ISSUE THREAD

**Issue by moebiussurfing** [pegvin/ImGooeyStyles#1]
Hello @pegvin , 
Thanks for sharing.

I am trying to make it work into a project, but I am getting an error in `LOAD_IMVEC2s`.

Do you know how could be fixed?

![image](https://user-images.githubusercontent.com/2106149/231319502-69caddac-4624-4da2-a41c-ae65a6e30470.png)

![image](https://user-images.githubusercontent.com/2106149/231319535-a62c2e20-b6e0-4020-9ef5-3b99e2012258.png)

**Comment by pegvin** [comment]
will fixes the issue asap.

**Comment by moebiussurfing** [comment]
Now it works like that:

```.cpp
#define LOAD_IMVEC2s(var_imvec2, name) { \
    const char* str = ini_get(ini_style, "ImGuiStyles", #name); \
    if (str != NULL) { \
        char str_copy[256]; \
        strncpy(str_copy, str, sizeof(str_copy)); \
        char* CommaOffset = strchr(str_copy, ','); \
        if (CommaOffset != NULL) { \
            *CommaOffset = '\0'; \
            var_imvec2.x = atof(str_copy); \
            var_imvec2.y = atof(CommaOffset + 1); \
        } \
    } \
}
```

Chat Gpt did it. and also some small changes:


> Here's what I've changed:
> 
> I've added some whitespace to make the macro definition more readable.
> I've removed the BeforeComma variable and instead used the strchr function to find the comma offset directly.
> I've added some checks to handle cases where the ini_get function returns NULL or where the comma offset is not found.
> I've added a line to set the comma character to the null terminator ('\0') to split the string into two parts before and after the comma.


--


> The error message you're seeing is because the strchr function expects a non-const char* pointer as its first argument, but the ini_get function returns a const char* pointer. In this case, the macro definition is trying to modify the contents of the string pointed to by the const char* pointer, which is not allowed.
> 
> To fix this issue, you can make a copy of the string returned by ini_get and modify that instead. Here's an updated version of the macro definition that should work:

**Comment by pegvin** [comment]
i was aware of the issue way before the Issue was raised, just didn't have the time to act.

will close the issue when it's fixed.

**Comment by moebiussurfing** [comment]
PS

I have seen your blog post about your undo engine.
Do you think it could be used on a theme editor like this?

I am thinking in other features/ideas, 
Let me paste some ideas from [my repo](https://github.com/moebiussurfing/ofxSurfingImGui/blob/edbf58fe187adb2fe4f10353f6e13a2fb45effcf/Examples/09_ThemeEditor/README.md) TODO notes if you don't mind:

```
- Add apply by sections: 
sizes and layout and/or colors.

- Define a global color/accent color, and some related 2/3 main colors.
link colors between particular settings.
(to edit many at once) but darker or lighter. 
ex: mark what colors must be linked. 
And each one has his own alpha.

- Add a reset theme and A/B compare 
and store/recall.

- Undo history or snapshot points. 
(using ofParams and an addon for presets.)
```

OTHER LINKS

This app allow copy paste themes and there's many bundled themes too, if you are interested.
https://github.com/Patitotective/ImThemes
https://github.com/Patitotective/ImStyle

**Comment by pegvin** [comment]
thanks for the ideas but i want to keep the library simple and allow others to build on top of it.

also closing the issue since i've patched it, but feel free to open a new issue if you want to discuss more! i hope this doesn't feel rude.

One Love.
